version: '3.5'

services:

  api:
    image: golang:latest
    volumes:
      - ./:/api

    entrypoint: /bin/sh -c "cd /api && go build -o server cmd/main.go && /api/server"
    environment:
       DSN: mongodb://mongo:27017/
       DB: crud
       TABLE: users
       FILE: DataSet
       USERNAME: root
       PASSWORD: example
    ports:
      - 8080:8080
    networks:
      - internal

  mongo:
    container_name: "mongo"
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: crud
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - internal
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - internal
networks:
  internal:
    name: internal